branches:
  only:
    - master
    - develop
    
init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"
   
test: off

build:
  project: src\Wyam.sln
  publish_nuget: true

cache:
- src\packages -> src\**\packages.config
- tools -> tools\packages.config
  
on_failure:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"
